name: build

on:
  push:
    branches-ignore:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 12.13.0
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'

    - run: yarn install

    - run: yarn lint

    - run: yarn test

    - run: yarn build

    - run: yarn build-storybook
