name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - uses: bahmutov/npm-install@v1
    - run: yarn lint
    - run: yarn test
    - run: yarn build

  storybook:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        # Required to retrieve git history for Chromatic
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
    - uses: bahmutov/npm-install@v1
    - run: yarn chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }} --auto-accept-changes '{master|test}'
